version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    target-branch: main
    open-pull-requests-limit: 100
    commit-message:
      prefix: BAU
